### ISSUE TITLE
Feature request: Double-click to play station

### ISSUE THREAD

**Issue by canadaduane** [alexkdeveloper/somafm#10]
Love this app!

I wonder if it would make sense to be able to double-click to play a station? Or similarly, to be able to press "enter" or "spacebar" to play a station (up/down arrow keys already move the highlight up/down)?

**Comment by alexkdeveloper** [comment]
Perhaps this will be added in future releases.

**Comment by alexkdeveloper** [comment]
The ability to start or stop the playback of stations by pressing the space bar or enter will be available in the next release. The necessary changes have already been made to the application source code repository.

**Comment by alexkdeveloper** [comment]
Version 1.2.4 has been re-released and will be available in a few hours.

**Comment by riker09** [comment]
Still no double-click to play? (I'm on version 1.2.7 from Flathub)
